package Interfaces;
import Business.MyFavCar;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
* Date    09-11-2019
 * @author rashmirj
 * 
 * Details
 * Define panel, here, a set of text fields collect user inputs for the various car attributes
 * The user input values are set to the car object defined in the business package
 * An option to upload an image is also provided in this panel. 
 * pre-filtered file values accepted are jpg and png. 
 * Once uploaded, the absolute file path is stored onto a variable from the car object. 
 */
public class DefinePanel extends javax.swing.JPanel {

    
    private MyFavCar myFavCar;
   
    public DefinePanel(MyFavCar myFavCar) {
        initComponents();
        this.myFavCar = myFavCar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        brandTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        costTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        serialNumTextField = new javax.swing.JTextField();
        dimensionsTextField = new javax.swing.JTextField();
        gearTypeTextField = new javax.swing.JTextField();
        numOfSeatsTextField = new javax.swing.JTextField();
        carTypeTextField = new javax.swing.JTextField();
        yearManufacturedTextField = new javax.swing.JTextField();
        hasABSTextField = new javax.swing.JTextField();
        grossWtTextField = new javax.swing.JTextField();
        mileageTextField = new javax.swing.JTextField();
        hasNavSystemTextField = new javax.swing.JTextField();
        defineButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        browseImageButton = new javax.swing.JButton();
        fileUploadedLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Define the details of your favorite car below");

        jLabel2.setText("Name:");

        jLabel3.setText("Brand:");

        jLabel4.setText("Cost:");

        jLabel5.setText("Model Number:");

        jLabel6.setText("Dimensions (L X B):");

        jLabel7.setText("Gear Type:");

        jLabel8.setText("Serial Number:");

        jLabel9.setText("Color:");

        jLabel11.setText("Has Navigation System:");

        jLabel12.setText("Mileage:");

        jLabel13.setText("Gross weight:");

        jLabel14.setText("Has ABS:");

        jLabel15.setText("Year Manufactured:");

        jLabel16.setText("Car Type:");

        jLabel17.setText("Number of Seats:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        brandTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextFieldActionPerformed(evt);
            }
        });

        modelNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNumTextFieldActionPerformed(evt);
            }
        });

        costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTextFieldActionPerformed(evt);
            }
        });

        colorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextFieldActionPerformed(evt);
            }
        });

        serialNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumTextFieldActionPerformed(evt);
            }
        });

        dimensionsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionsTextFieldActionPerformed(evt);
            }
        });

        gearTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gearTypeTextFieldActionPerformed(evt);
            }
        });

        numOfSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfSeatsTextFieldActionPerformed(evt);
            }
        });

        carTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeTextFieldActionPerformed(evt);
            }
        });

        yearManufacturedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearManufacturedTextFieldActionPerformed(evt);
            }
        });

        hasABSTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasABSTextFieldActionPerformed(evt);
            }
        });

        grossWtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossWtTextFieldActionPerformed(evt);
            }
        });

        mileageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileageTextFieldActionPerformed(evt);
            }
        });

        hasNavSystemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasNavSystemTextFieldActionPerformed(evt);
            }
        });

        defineButton.setText("Done");
        defineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defineButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Upload Image:");

        browseImageButton.setText("Browse Images");
        browseImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(140, 140, 140)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(140, 140, 140)
                        .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(90, 90, 90)
                        .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(148, 148, 148)
                        .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(143, 143, 143)
                        .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(91, 91, 91)
                        .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(65, 65, 65)
                        .addComponent(dimensionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(114, 114, 114)
                        .addComponent(gearTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(77, 77, 77)
                        .addComponent(numOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(121, 121, 121)
                        .addComponent(carTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(65, 65, 65)
                        .addComponent(yearManufacturedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(125, 125, 125)
                        .addComponent(hasABSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(99, 99, 99)
                        .addComponent(grossWtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(129, 129, 129)
                        .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(defineButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(94, 94, 94)
                                .addComponent(browseImageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileUploadedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(43, 43, 43)
                                .addComponent(hasNavSystemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(dimensionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(gearTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(numOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(carTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(yearManufacturedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(hasABSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(grossWtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(hasNavSystemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileUploadedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel18))
                    .addComponent(browseImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(defineButton))
        );

        brandTextField.getAccessibleContext().setAccessibleParent(nameTextField);

        getAccessibleContext().setAccessibleParent(hasNavSystemTextField);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void brandTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTextFieldActionPerformed

    private void modelNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNumTextFieldActionPerformed

    private void costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costTextFieldActionPerformed

    private void colorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextFieldActionPerformed

    private void serialNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumTextFieldActionPerformed

    private void dimensionsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionsTextFieldActionPerformed

    private void gearTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gearTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gearTypeTextFieldActionPerformed

    private void numOfSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfSeatsTextFieldActionPerformed

    private void carTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeTextFieldActionPerformed

    private void yearManufacturedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearManufacturedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearManufacturedTextFieldActionPerformed

    private void hasABSTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasABSTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasABSTextFieldActionPerformed

    private void grossWtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossWtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossWtTextFieldActionPerformed

    private void mileageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileageTextFieldActionPerformed

    private void hasNavSystemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasNavSystemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasNavSystemTextFieldActionPerformed

    private void defineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defineButtonActionPerformed
            // on pressing "Done", the values from the text boxes are passed on to the car object using it's setter methods
            myFavCar.setName(nameTextField.getText()); 
            myFavCar.setBrand(brandTextField.getText()); 
            myFavCar.setModelNum(modelNumTextField.getText()); 
            myFavCar.setCost(costTextField.getText()); 
            myFavCar.setColor(colorTextField.getText()); 		
            myFavCar.setSerialNum(serialNumTextField.getText()); 
            myFavCar.setDimensions(dimensionsTextField.getText()); 
            myFavCar.setGearType(gearTypeTextField.getText()); 
            myFavCar.setNumOfSeats(numOfSeatsTextField.getText()); 
            myFavCar.setCarType(carTypeTextField.getText());
            myFavCar.setYearManufactured(yearManufacturedTextField.getText()); 
            myFavCar.setHasABS(hasABSTextField.getText()); 
            myFavCar.setGrossWt(grossWtTextField.getText()); 
            myFavCar.setMileage(mileageTextField.getText());
            myFavCar.setHasNavSystem(hasNavSystemTextField.getText());          
            
            //on save, prompt user that product was successfully saved
            JOptionPane.showMessageDialog(null, "Defined favorite car successfully");
    }//GEN-LAST:event_defineButtonActionPerformed

    
    private void browseImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageButtonActionPerformed
          JFileChooser file = new JFileChooser();
          //on load of file chooser, show only image file formats for the user to choose files from. 
          //helps in reducing time spent by the user to look for images specifically
          //also reduces human error by choosing wrong file types
          FileNameExtensionFilter fileFormatFilter = new FileNameExtensionFilter("ImageFiles",ImageIO.getReaderFileSuffixes());
          file.setFileFilter(fileFormatFilter);
          int result = file.showOpenDialog(new JPanel());
           //if the user click on save in Jfilechooser, then set the absolute image path to the myFavCar object's path variable so that path can be retrived during "View" Operation
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String selectedFilePath = selectedFile.getAbsolutePath();
              myFavCar.setImgPath(selectedFilePath);
              fileUploadedLabel.setText("File Uploaded"); //to convey that a file was uploaded
          }
          else if(result == JFileChooser.CANCEL_OPTION){
               fileUploadedLabel.setText("No File Uploaded"); // to convey that user has not chosen any file
          }       
    }//GEN-LAST:event_browseImageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandTextField;
    private javax.swing.JButton browseImageButton;
    private javax.swing.JTextField carTypeTextField;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField costTextField;
    private javax.swing.JButton defineButton;
    private javax.swing.JTextField dimensionsTextField;
    private javax.swing.JLabel fileUploadedLabel;
    private javax.swing.JTextField gearTypeTextField;
    private javax.swing.JTextField grossWtTextField;
    private javax.swing.JTextField hasABSTextField;
    private javax.swing.JTextField hasNavSystemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mileageTextField;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField numOfSeatsTextField;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JTextField yearManufacturedTextField;
    // End of variables declaration//GEN-END:variables
}
