/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.TravelAgency.BookFlightsPanel;
import UserInterface.Airliner.ManageAirlinerPanel;
import UserInterface.Flights.ManageFlightsPanel;
import UserInterface.Customer.ManageCustomerPanel;
import UserInterface.TravelAgency.ManageBookingsPanel;
import Business.Business;
import Business.ConfigureABusiness;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import Business.Airline.AirlinerDirectory;
import Business.TravelAgency.Booking;
import Business.TravelAgency.BookingDirectory;
import Business.Customer.CustomerDirectory;
import Business.Flights.Flight;
import Business.Flights.FlightDirectory;
import Business.TravelAgency.Seat;
import Business.TravelAgency.SeatDirectory;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author DivyaThanigaiArasu
 */
public class MainJFrame extends javax.swing.JFrame {

    private AirlinerDirectory alnDir;
    private FlightDirectory fltDir;
    private BookingDirectory bookDir;
    private CustomerDirectory custDir;
    private Flight flight;
    private Booking booking;
    private SeatDirectory seatDir;
    private ArrayList<Seat> seatList;
    /**
     * Creates new form MainJFrame
     */
    private Business business;

    public MainJFrame() {
        initComponents();
        business = ConfigureABusiness.configure();
        this.alnDir = new AirlinerDirectory();
        this.fltDir = new FlightDirectory();
        this.bookDir = new BookingDirectory();
        this.custDir = new CustomerDirectory();
        this.flight = flight;
        this.booking = booking;
        this.seatDir = seatDir;
        this.seatList = seatList;
        btnManageAirliner.setVisible(false);
        btnBookFlight.setVisible(false);
        btnManageBookings.setVisible(false);
        btnManageFlightScdl.setVisible(false);
        btnManageCustomer.setVisible(false);
        btnLogout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblUname = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        lblPwd = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pswdField = new javax.swing.JPasswordField();
        btnManageAirliner = new javax.swing.JButton();
        btnBookFlight = new javax.swing.JButton();
        btnManageFlightScdl = new javax.swing.JButton();
        btnManageBookings = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 755));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 755));

        lblUname.setText("Username");

        lblPwd.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        pswdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdFieldActionPerformed(evt);
            }
        });

        btnManageAirliner.setText("Manage Airliners");
        btnManageAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinerActionPerformed(evt);
            }
        });

        btnBookFlight.setText("Book Flights");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnManageFlightScdl.setText("Manage Flights");
        btnManageFlightScdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightScdlActionPerformed(evt);
            }
        });

        btnManageBookings.setText("Manage Bookings");
        btnManageBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookingsActionPerformed(evt);
            }
        });

        btnManageCustomer.setText("Manage Customers");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswdField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBookFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnManageBookings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPwd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnManageAirliner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageFlightScdl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addGap(1, 1, 1)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageAirliner)
                .addGap(2, 2, 2)
                .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageFlightScdl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageBookings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageCustomer)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        rightPanel.setAutoscrolls(true);
        rightPanel.setMinimumSize(new java.awt.Dimension(950, 750));
        rightPanel.setPreferredSize(new java.awt.Dimension(950, 750));
        rightPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String userName = txtUname.getText();
        char[] pass = pswdField.getPassword();
        String password = String.valueOf(pass);
        boolean flag = false;
        btnLogout.setVisible(true);

        UserAccount userAccount = null;
        for (Organization organization : business.getOrganizationDirectory().getOrganizationList()) {
            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
            if (userAccount != null) {
                flag = true;
                btnLogin.setVisible(false);
                btnLogout.setEnabled(true);
                lblUname.setVisible(false);
                lblPwd.setVisible(false);
                txtUname.setVisible(false);
                pswdField.setVisible(false);

                if (userAccount.getRole() == "Admin") {
                    btnManageAirliner.setVisible(true);
                    btnManageFlightScdl.setVisible(true);
                    btnBookFlight.setVisible(false);
                    btnManageBookings.setVisible(false);
                    btnManageCustomer.setVisible(false);
                }

                if (userAccount.getRole() == "TravelAgency") {
                    btnBookFlight.setVisible(true);
                    btnManageBookings.setVisible(true);
                    btnManageFlightScdl.setVisible(false);
                    btnManageAirliner.setVisible(false);
                    btnManageCustomer.setVisible(true);
                }
                break;
            }

        }

        if (flag == false) {
            txtUname.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblUname.setForeground(Color.red);
            pswdField.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblPwd.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Invalid username or password");
            return;
        }

        LogInScreen login = new LogInScreen(rightPanel);
        rightPanel.add("LoginScreen", login);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnLogout.setEnabled(false);
        lblUname.setVisible(true);
        lblPwd.setVisible(true);
        txtUname.setVisible(true);
        pswdField.setVisible(true);
        btnLogin.setVisible(true);
        btnBookFlight.setVisible(false);
        btnManageAirliner.setVisible(false);
        btnManageFlightScdl.setVisible(false);
        btnManageBookings.setVisible(false);
        btnManageCustomer.setVisible(false);
        btnLogout.setVisible(false);
        txtUname.setText("");
        pswdField.setText("");
        LogOutScreen logout = new LogOutScreen(rightPanel);
        rightPanel.add("LogoutScreen", logout);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void pswdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdFieldActionPerformed

    private void btnManageAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinerActionPerformed
        // TODO add your handling code here:       
        //rashmiTODO check how to remove all Jpanels from cardLayout here
        ManageAirlinerPanel manageAlrPanel = new ManageAirlinerPanel(rightPanel, alnDir);
        rightPanel.add("manageAirlinerPanel", manageAlrPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageAirlinerActionPerformed

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        BookFlightsPanel manageCustPanel = new BookFlightsPanel(rightPanel, fltDir, bookDir, custDir);
        rightPanel.add("manageCustomerPanel", manageCustPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnManageFlightScdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightScdlActionPerformed
        ManageFlightsPanel manageFlPanel = new ManageFlightsPanel(rightPanel, fltDir, alnDir);
        rightPanel.add("manageFlightsPanel", manageFlPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);


    }//GEN-LAST:event_btnManageFlightScdlActionPerformed

    private void btnManageBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookingsActionPerformed
        // TODO add your handling code here:
        ManageBookingsPanel manageBookings = new ManageBookingsPanel(rightPanel, bookDir, fltDir, booking);//, seatDir , seatList );
        rightPanel.add("ManageBookingsPanel", manageBookings);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageBookingsActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        ManageCustomerPanel mcPanel = new ManageCustomerPanel(rightPanel, custDir);
        rightPanel.add("ManageCustomerPanel", mcPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAirliner;
    private javax.swing.JButton btnManageBookings;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageFlightScdl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPasswordField pswdField;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
