/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.TravelAgency.Booking;
import Business.TravelAgency.BookingDirectory;
import Business.Flights.Flight;
import Business.Flights.FlightDirectory;
import Business.Customer.Passenger;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shriya22
 */
public class UpdateBookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateBookingPanel
     */
    private JPanel rightPanel;
    private BookingDirectory bookDir;
    private FlightDirectory fltDir;
    private Flight flight;
    private Passenger passenger;
    private Booking booking;
    private Date d;

    UpdateBookingPanel(JPanel rightPanel, Booking booking, BookingDirectory bookDir, Passenger passenger, FlightDirectory fltDir, Flight flight) {
        initComponents();
        this.rightPanel = rightPanel;
        this.d = new Date();
        this.bookDir = bookDir;
        this.booking = booking;
        this.fltDir = fltDir;
        this.flight = flight;
        lblTime.setVisible(false);
        txtTime.setVisible(false);
        populateFlightDetails();

    }

    private void populateFlightDetails() {
        txtBookRef.setText(String.valueOf(booking.getBookingReference()));
        txtFlNumber.setText(String.valueOf(booking.getFlightNumber()));
        txtFlightName.setText(booking.getFlightName());
        txtSource.setText(booking.getSource());
        txtFTravellerNumber.setText(String.valueOf(booking.getPassengerNumber()));
        txtDestination.setText(booking.getDestination());
    }

    private void populateSearchresults(List<Flight> result) {
        DefaultTableModel dtm = (DefaultTableModel) tblFlightSched.getModel();
        dtm.setRowCount(0);
        for (Flight b : result) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = b.getFlAirlinerName();
            row[1] = b.getFlNumber();
            row[2] = b.getFlDate();
            row[3] = b.getFlFlyingTime();

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlName = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        txtFlNumber = new javax.swing.JTextField();
        lblFlNumber = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        lblSource = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblSource1 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        txtFTravellerNumber = new javax.swing.JTextField();
        lblNoOfTravellers = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtBookRef = new javax.swing.JTextField();
        lblTCost = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightSched = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();

        lblFlName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlName.setText("Flight Name:");

        txtFlightName.setEditable(false);

        txtFlNumber.setEditable(false);

        lblFlNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlNumber.setText("Flight number:");

        txtSource.setEditable(false);

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSource.setText("Source:");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setText("Departing Date:");

        lblSource1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSource1.setText("Destination:");

        txtDestination.setEditable(false);

        txtFTravellerNumber.setEditable(false);

        lblNoOfTravellers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoOfTravellers.setText("No. of Travellers:");

        txtBookRef.setEditable(false);

        lblTCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTCost.setText("Booking Reference :");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Update Booking Details");

        tblFlightSched.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline", "Flight number", "Departure Date", "Departure Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFlightSched);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update Booking");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setText("Departing Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(lblTitle)
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTCost)
                                .addGap(18, 18, 18)
                                .addComponent(txtBookRef, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblFlNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFlName)
                                    .addComponent(lblSource)
                                    .addComponent(lblDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(lblSource1))
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFlNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTime)
                            .addComponent(lblNoOfTravellers))
                        .addGap(34, 34, 34)
                        .addComponent(txtFTravellerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnUpdate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTCost)
                    .addComponent(lblFlNumber)
                    .addComponent(txtFlNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlName)
                    .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSource1)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFTravellerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoOfTravellers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnUpdate)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);

        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageBookingsPanel) {
                ManageBookingsPanel manageBookPanel = (ManageBookingsPanel) comp;
                manageBookPanel.populate(bookDir.getBookingList());
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tblFlightSched.setVisible(true);

        String date = txtDate.getText();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        if (date == null || date.equals("")) {
            JOptionPane.showMessageDialog(null, "Date cannot be empty");
            txtDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblDate.setForeground(Color.red);
            return;
        }
        Date chosenDate = null;
        try {
            chosenDate = s.parse(txtDate.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter date in YYYY-MM-DD format");
            txtDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblDate.setForeground(Color.red);
            return;

        }
        if (chosenDate.before(d)) {
            JOptionPane.showMessageDialog(null, "Date cannot be before current date");
            txtDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblDate.setForeground(Color.red);
            return;
        }

        List<Flight> result = fltDir.searchFlight2(txtFlightName.getText(), txtSource.getText(), txtDestination.getText(), txtDate.getText());
        if (result.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid search result", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populateSearchresults(result);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        lblTime.setVisible(true);
        txtTime.setVisible(true);
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        int selectedRow = tblFlightSched.getSelectedRow();
        if (selectedRow >= 0) {
            Flight flight = (Flight) tblFlightSched.getValueAt(selectedRow, 0);
            txtTime.setText(flight.getFlFlyingTime());
            txtDate.setText(String.valueOf(flight.getFlDate()));

            booking.setFlyingTime(txtTime.getText());
            try {
                booking.setStartDate(s.parse(txtDate.getText()));
            } catch (ParseException ex) {

            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlName;
    private javax.swing.JLabel lblFlNumber;
    private javax.swing.JLabel lblNoOfTravellers;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblSource1;
    private javax.swing.JLabel lblTCost;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFlightSched;
    private javax.swing.JTextField txtBookRef;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFTravellerNumber;
    private javax.swing.JTextField txtFlNumber;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

}
