/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.TravelAgency.Booking;
import Business.TravelAgency.BookingDirectory;
import Business.Customer.CustomerDirectory;
import Business.Customer.Passenger;
import Business.TravelAgency.Seat;
import UserInterface.Flights.ManageFlightsPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shriya22
 */
public class ViewBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBookingJPanel
     */
    private Booking booking;
    private JPanel rightpanel;
    private BookingDirectory bookDir;
    private Passenger passenger;
    private CustomerDirectory customerList;
    private Seat seat;

    public ViewBookingJPanel(JPanel rightpanel, Booking booking, BookingDirectory bookDir, Passenger passenger, Seat seat) {
        initComponents();
        this.rightpanel = rightpanel;
        this.booking = booking;
        this.bookDir = bookDir;
        this.passenger = passenger;
        this.seat = seat;
        populateBookingDetails();
    }

    private void populateBookingDetails() {
        txtBookingRef.setText(String.valueOf(booking.getBookingReference()));
        txtFlNumber.setText(String.valueOf(booking.getFlightNumber()));
        txtFlightName.setText(booking.getFlightName());
        txtDate.setText(String.valueOf(booking.getStartDate()));
        txtFTravellerNumber.setText(String.valueOf(booking.getPassengerNumber()));

        DefaultTableModel dtm = (DefaultTableModel) tblPassenger.getModel();
        dtm.setRowCount(0);

        for (Passenger p : booking.getPassengerList()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = p.getName();
            row[1] = p.getAge();
            row[2] = p.getSeat();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFlName = new javax.swing.JLabel();
        lblFlNumber = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtFlNumber = new javax.swing.JTextField();
        txtFTravellerNumber = new javax.swing.JTextField();
        lblNoOfTravellers = new javax.swing.JLabel();
        lblFlName1 = new javax.swing.JLabel();
        txtBookingRef = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPassenger = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Booking Details");

        lblFlName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlName.setText("Flight Name:");

        lblFlNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlNumber.setText("Flight number:");

        txtFlightName.setEditable(false);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setText("Departing Date:");

        txtDate.setEditable(false);

        txtFlNumber.setEditable(false);

        txtFTravellerNumber.setEditable(false);

        lblNoOfTravellers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoOfTravellers.setText("No. of Travellers:");

        lblFlName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlName1.setText("Booking Reference:");

        txtBookingRef.setEditable(false);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblPassenger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger Name", "Passenger Age", "SeatNumber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPassenger);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlName1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBookingRef, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFlNumber)
                            .addComponent(lblNoOfTravellers))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFlNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFTravellerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBookingRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFlName1)
                            .addComponent(lblFlNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFlName)
                            .addComponent(lblNoOfTravellers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFlNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFTravellerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);

        Component[] comps = this.rightpanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageFlightsPanel) {
                ManageBookingsPanel manageBookPanel = (ManageBookingsPanel) comp;
                manageBookPanel.populate(bookDir.getBookingList());
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlName;
    private javax.swing.JLabel lblFlName1;
    private javax.swing.JLabel lblFlNumber;
    private javax.swing.JLabel lblNoOfTravellers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPassenger;
    private javax.swing.JTextField txtBookingRef;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFTravellerNumber;
    private javax.swing.JTextField txtFlNumber;
    private javax.swing.JTextField txtFlightName;
    // End of variables declaration//GEN-END:variables

}
