/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airline.Airliner;
import Business.Airline.AirlinerDirectory;
import Business.Airline.Airplane;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashmirj
 */
public class CreateAirlinerPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private AirlinerDirectory alnDir;
    private Airliner alr;
    private ArrayList<Airplane> alpList;

    /**
     * Creates new form CreateAirlinerPanel
     */
    public CreateAirlinerPanel(JPanel rightPanel, AirlinerDirectory alnDir) {
        this.alnDir = alnDir;
        this.rightPanel = rightPanel;
        this.alr = new Airliner();
        this.alpList = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAirplaneCount = new javax.swing.JLabel();
        txtAlrName = new javax.swing.JTextField();
        txtAlrAddr = new javax.swing.JTextField();
        txtAlrCity = new javax.swing.JTextField();
        txtAlrState = new javax.swing.JTextField();
        txtAlrCountry = new javax.swing.JTextField();
        txtAlrZip = new javax.swing.JTextField();
        btnAddAirplane = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplane = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnDeleteAirplane = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Airliner");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name:");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Street Address: ");

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblState.setText("State:");

        lblCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCountry.setText("Country:");

        lblZip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblZip.setText("Zip:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("No. Of Airplanes:");

        lblAirplaneCount.setText(" ");

        btnAddAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddAirplane.setText("Add Airplane to Airline");
        btnAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirplaneActionPerformed(evt);
            }
        });

        tblAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Type", "Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirplane);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Airplanes Added:");

        btnDeleteAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteAirplane.setText("Remove Airplane");
        btnDeleteAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirplaneActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(323, 323, 323)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblName)
                            .addComponent(lblAddress)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(lblCountry)
                            .addComponent(lblZip)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlrZip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlrCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAirplaneCount)
                                .addGap(167, 167, 167)
                                .addComponent(btnAddAirplane))
                            .addComponent(txtAlrState, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlrCity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAlrName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlrAddr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtAlrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAlrAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtAlrCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtAlrState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtAlrCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZip)
                    .addComponent(txtAlrZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblAirplaneCount)
                    .addComponent(btnAddAirplane))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteAirplane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateNewPlanes() {
        DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
        dtm.setRowCount(0);
        if (alpList.size() != 0) {
            for (Airplane a : alpList) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = a;
                row[1] = a.getAlnType();
                row[2] = a.getAlnCapacity();
                dtm.addRow(row);
            }
        }
    }

    public void populateNewPlanes(ArrayList<Airplane> p) {
        DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
        dtm.setRowCount(0);

        for (Airplane a : p) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getAlnType();
            row[2] = a.getAlnCapacity();
            dtm.addRow(row);
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageAirlinerPanel) {
                ManageAirlinerPanel manageA = (ManageAirlinerPanel) comp;
                manageA.populate(alnDir.getAirlinerList());
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirplaneActionPerformed
        CreateAirplanePanel createAirplanePanel = new CreateAirplanePanel(rightPanel, alnDir, alpList, "create");
        rightPanel.add("createAirplanePanel", createAirplanePanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnAddAirplaneActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String name = txtAlrName.getText();
        if (name == null || name.equals("")) {
            JOptionPane.showMessageDialog(null, "Airliner name can't be empty");
            txtAlrName.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblName.setForeground(Color.red);
            return;
        } else if (!name.matches("^[a-zA-Z_ ]*$")) {
            JOptionPane.showMessageDialog(null, "Airliner name must contain only alphabets");
            txtAlrName.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblName.setForeground(Color.red);
            return;
        }
        String stAddress = txtAlrAddr.getText();
        if (stAddress == null || stAddress.equals("")) {
            JOptionPane.showMessageDialog(null, "Street address can't be empty");
            txtAlrAddr.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblAddress.setForeground(Color.red);
            return;
        }
        String city = txtAlrCity.getText();
        if (city == null || city.equals("")) {
            JOptionPane.showMessageDialog(null, "City can't be empty");
            txtAlrCity.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblCity.setForeground(Color.red);
            return;
        } else if (!city.matches("^[a-zA-Z_ ]*$")) {
            JOptionPane.showMessageDialog(null, "City name must contain only alphabets");
            txtAlrCity.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblCity.setForeground(Color.red);
            return;
        }
        String state = txtAlrState.getText();
        if (state == null || state.equals("")) {
            JOptionPane.showMessageDialog(null, "State can't be empty");
            txtAlrState.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblState.setForeground(Color.red);
            return;
        } else if (!state.matches("^[a-zA-Z_ ]*$")) {
            JOptionPane.showMessageDialog(null, "State name must contain only alphabets");
            txtAlrState.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblState.setForeground(Color.red);
            return;
        }
        String country = txtAlrCountry.getText();
        if (country == null || country.equals("")) {
            JOptionPane.showMessageDialog(null, "Country name can't be empty");
            txtAlrCountry.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblCountry.setForeground(Color.red);
            return;
        } else if (!country.matches("^[a-zA-Z_ ]*$")) {
            JOptionPane.showMessageDialog(null, "Country name must contain only alphabets");
            txtAlrCountry.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblCountry.setForeground(Color.red);
            return;
        }
        String zip = txtAlrZip.getText();
        try {
            Integer.parseInt(zip);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter number for zipcode");
            txtAlrZip.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblZip.setForeground(Color.red);
            return;
        }
        
        if(alpList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add atleast one airplane to the airliner");
            return;
        }
        
        txtAlrName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblName.setForeground(Color.BLACK);
        txtAlrAddr.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblAddress.setForeground(Color.BLACK);
        txtAlrState.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblState.setForeground(Color.BLACK);
        txtAlrCountry.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblCountry.setForeground(Color.BLACK);
        txtAlrZip.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblZip.setForeground(Color.BLACK);

        Airliner airlinerBrand = alnDir.addAirliner();
        airlinerBrand.setAlrPlanes(alpList);
        airlinerBrand.setAlrName(name);
        airlinerBrand.setAlrAddress(stAddress);
        airlinerBrand.setAlrCity(city);
        airlinerBrand.setAlrState(state);
        airlinerBrand.setAlrCountry(country);
        airlinerBrand.setAlrZipCode(zip);
        JOptionPane.showMessageDialog(null, "Airliner Created Successfully");

        txtAlrName.setText("");
        txtAlrAddr.setText("");
        txtAlrCity.setText("");
        txtAlrState.setText("");
        txtAlrCountry.setText("");
        txtAlrZip.setText("");
        DefaultTableModel dm = (DefaultTableModel) tblAirplane.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirplaneActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAirplane.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete airplane??", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                Airplane plane = (Airplane) tblAirplane.getValueAt(selectedRow, 0);
                alpList.remove(plane);
                populateNewPlanes();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Airplane");
        }
    }//GEN-LAST:event_btnDeleteAirplaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirplane;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeleteAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAirplaneCount;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTable tblAirplane;
    private javax.swing.JTextField txtAlrAddr;
    private javax.swing.JTextField txtAlrCity;
    private javax.swing.JTextField txtAlrCountry;
    private javax.swing.JTextField txtAlrName;
    private javax.swing.JTextField txtAlrState;
    private javax.swing.JTextField txtAlrZip;
    // End of variables declaration//GEN-END:variables
}
