/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airline.AirlinerDirectory;
import Business.Airline.Airplane;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rashmirj
 */
public class CreateAirplanePanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private AirlinerDirectory alnDir;
    private ArrayList<Airplane> alpList;
    private String screenName;

    /**
     * Creates new form CreateAirplanePanel
     */
    public CreateAirplanePanel(JPanel rightPanel, AirlinerDirectory alnDir, ArrayList<Airplane> alpList, String screenName) {
        initComponents();
        this.alnDir = alnDir;
        this.rightPanel = rightPanel;
        this.alpList = alpList;
        this.screenName = screenName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        btnCreateAirplane = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Airplane");

        lblNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumber.setText("Number:");

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setText("Type:");

        btnCreateAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateAirplane.setText("Create");
        btnCreateAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirplaneActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateAirplane)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblType)
                            .addComponent(lblNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnCreateAirplane)
                .addContainerGap(525, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);

        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (screenName.equals("create")) {
                if (comp instanceof CreateAirlinerPanel) {
                    CreateAirlinerPanel alrCreatePanel = (CreateAirlinerPanel) comp;
                    alrCreatePanel.populateNewPlanes(alpList);
                }
            } else if (screenName.equals("update")) {
                if (comp instanceof UpdateAirlinerPanel) {
                    UpdateAirlinerPanel alrUpdatePanel = (UpdateAirlinerPanel) comp;
                    alrUpdatePanel.populatePlanes(alpList);
                }
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirplaneActionPerformed
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtNumber.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter number for airplane number");
            txtNumber.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblNumber.setForeground(Color.red);
            return;
        }

        String type = txtType.getText();
        if (type == null || type.equals("")) {
            JOptionPane.showMessageDialog(null, "Airplane type can't be empty");
            txtType.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblType.setForeground(Color.red);
            return;
        } else if (!type.matches("^[a-zA-Z0-9_ ]*$")) {
            JOptionPane.showMessageDialog(null, "Airplane type name can contain either alphabets or numbers");
            txtType.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblType.setForeground(Color.red);
            return;
        }
        txtType.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblType.setForeground(Color.BLACK);
        txtNumber.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblNumber.setForeground(Color.BLACK);

        Airplane alp = new Airplane();
        alp.setAlnNumber(Integer.parseInt(txtNumber.getText()));
        alp.setAlnType(type);
        alp.setAlnCapacity(50);

        alpList.add(alp);

        JOptionPane.showMessageDialog(null, "Airplane Successfully created.");

        txtNumber.setText("");
        txtType.setText("");
    }//GEN-LAST:event_btnCreateAirplaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
