/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airline.Airliner;
import Business.Airline.Airplane;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rashmirj
 */
public class UpdateAirplanePanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private Airplane alp;
    private Airliner alr;

    /**
     * Creates new form UpdateAirplanePanel
     */
    public UpdateAirplanePanel(JPanel rightPanel, Airplane alp, Airliner alr) {
        this.rightPanel = rightPanel;
        this.alp = alp;
        this.alr = alr;
        initComponents();
        txtNumber.setText(String.valueOf(alp.getAlnNumber()));
        txtType.setText(String.valueOf(alp.getAlnType()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumber = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        btnUpdateAirplane = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        btnCancelAirplane = new javax.swing.JButton();
        btnSaveAirplane = new javax.swing.JButton();

        txtNumber.setEnabled(false);

        txtType.setEnabled(false);

        btnUpdateAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateAirplane.setText("Update");
        btnUpdateAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirplaneActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Airplane");

        lblNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumber.setText("Number:");

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setText("Type:");

        btnCancelAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelAirplane.setText("Cancel");
        btnCancelAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAirplaneActionPerformed(evt);
            }
        });

        btnSaveAirplane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveAirplane.setText("Save");
        btnSaveAirplane.setEnabled(false);
        btnSaveAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAirplaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblType)
                            .addComponent(lblNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnSaveAirplane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateAirplane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelAirplane)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateAirplane)
                    .addComponent(btnCancelAirplane)
                    .addComponent(btnSaveAirplane))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);

        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof UpdateAirlinerPanel) {
                UpdateAirlinerPanel alrUpdatePanel = (UpdateAirlinerPanel) comp;
                alrUpdatePanel.populatePlanes(alr.getAlrPlanes());
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAirplaneActionPerformed
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtNumber.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter number for airplane number");
            txtNumber.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblNumber.setForeground(Color.red);
            return;
        }

        String type = txtType.getText();
        if (type == null || type.equals("")) {
            JOptionPane.showMessageDialog(null, "Airplane type can't be empty");
            txtType.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblType.setForeground(Color.red);
            return;
        } else if (!type.matches("^[a-zA-Z0-9_ ]*$")) {
            JOptionPane.showMessageDialog(null, "Airplane type name can contain either alphabets or numbers");
            txtType.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblType.setForeground(Color.red);
            return;
        }

        txtType.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblType.setForeground(Color.BLACK);
        txtNumber.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblNumber.setForeground(Color.BLACK);

        alp.setAlnNumber(Integer.parseInt(txtNumber.getText()));
        alp.setAlnType(type);

        JOptionPane.showMessageDialog(null, "Airplane Successfully updated.");
        txtNumber.setEnabled(false);
        txtType.setEnabled(false);
        btnSaveAirplane.setEnabled(false);
        btnUpdateAirplane.setEnabled(true);
    }//GEN-LAST:event_btnSaveAirplaneActionPerformed

    private void btnUpdateAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirplaneActionPerformed
        // TODO add your handling code here:
        txtNumber.setEnabled(true);
        txtType.setEnabled(true);
        btnSaveAirplane.setEnabled(true);
        btnUpdateAirplane.setEnabled(false);
    }//GEN-LAST:event_btnUpdateAirplaneActionPerformed

    private void btnCancelAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAirplaneActionPerformed
        // TODO add your handling code here:
        txtNumber.setText(String.valueOf(alp.getAlnNumber()));
        txtType.setText(String.valueOf(alp.getAlnType()));

        txtNumber.setEnabled(false);
        txtType.setEnabled(false);
        btnSaveAirplane.setEnabled(false);
        btnUpdateAirplane.setEnabled(true);
    }//GEN-LAST:event_btnCancelAirplaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelAirplane;
    private javax.swing.JButton btnSaveAirplane;
    private javax.swing.JButton btnUpdateAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
