/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarList;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Date: Oct 5 2019
 * @author rashmirj
 * 
 * Panel to create a new car
 * Validates inputs prior to proceeding to create a new car object
 * once created, clears the form for fresh input from the user
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private CarList carDir;
    private JPanel bottomPanel;

    public CreatePanel(JPanel bottomPanel, CarList carDir) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.carDir = carDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNew = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtMinSeats = new javax.swing.JTextField();
        lblRoutingNo = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        txtMfdYr = new javax.swing.JTextField();
        lblRoutingNo1 = new javax.swing.JLabel();
        lblAccNo1 = new javax.swing.JLabel();
        lblBankName1 = new javax.swing.JLabel();
        lblBankName2 = new javax.swing.JLabel();
        lblBalance2 = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        cbMaintenanceCert = new javax.swing.JCheckBox();
        cbAvailable = new javax.swing.JCheckBox();
        txtCity = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 153));

        btnAddNew.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNew.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 0, 153));
        btnAddNew.setText("Add Car");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        lblCreate.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblCreate.setText("Add new Car");

        lblAccNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAccNo.setForeground(new java.awt.Color(255, 255, 255));
        lblAccNo.setText("Model Number *");

        lblBankName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName.setText("Brand*");

        lblBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setText("Minimum Seats *");

        txtModelNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtBrand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtMinSeats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblRoutingNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo.setText("City *");

        txtMaxSeats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtMfdYr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblRoutingNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo1.setText("Maximum Seats *");

        lblAccNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAccNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccNo1.setText("Manufactured Year *");

        lblBankName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName1.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName1.setText("Maintenance Certification Done *");

        lblBankName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName2.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName2.setText("Available *");

        lblBalance2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance2.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance2.setText("Serial Number *");

        txtSerialNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        cbMaintenanceCert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        cbAvailable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtCity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnBack1.setBackground(new java.awt.Color(255, 255, 255));
        btnBack1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 0, 153));
        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoutingNo)
                            .addComponent(lblAccNo)
                            .addComponent(lblBankName)
                            .addComponent(lblBalance)
                            .addComponent(lblRoutingNo1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtModelNum)
                                    .addComponent(txtCity)
                                    .addComponent(txtBrand)
                                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAccNo1)
                                    .addComponent(lblBankName1))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMaintenanceCert)
                                    .addComponent(txtMfdYr, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBankName2)
                                    .addComponent(lblBalance2))
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAvailable)
                                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnAddNew))
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(lblCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(btnBack1)
                    .addContainerGap(1248, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCreate)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAccNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMfdYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBankName1)
                                    .addComponent(cbMaintenanceCert))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAvailable)
                                    .addComponent(lblBankName2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBalance2)
                                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRoutingNo)
                                .addGap(30, 30, 30)
                                .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblRoutingNo1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBankName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBalance))
                        .addGap(18, 18, 18)
                        .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(btnBack1)
                    .addContainerGap(695, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //Custom validations
        String cityCurr = txtCity.getText();
        String modelCurr = txtModelNum.getText();
        String brandCurr = txtBrand.getText();

        if (cityCurr == null || cityCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "City cannot be empty!");
            return;
        }

        if (modelCurr == null || modelCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "Model Number cannot be empty!");
            return;
        }
        if (brandCurr == null || brandCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "Brand cannot be empty!");
            return;
        }
        try {
            Integer.parseInt(txtMinSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid minimum number of seats!");
            return;
        }
        try {
            Integer.parseInt(txtMaxSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid maximum number of seats!!");
            return;
        }

        if (Integer.parseInt(txtMaxSeats.getText()) < Integer.parseInt(txtMinSeats.getText())) {
            JOptionPane.showMessageDialog(null, "Please ensure minimum is less than the maximum number of seats!!");
            return;
        }

        try {
            Integer.parseInt(txtMfdYr.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid Manufactured year for the car!");
            return;
        }

        try {
            Integer.parseInt(txtSerialNum.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid serial number!");
            return;
        }

        Car car = carDir.addCar();
        car.setCity(txtCity.getText());
        car.setModelNum(txtModelNum.getText());
        car.setBrand(txtBrand.getText());
        car.setMinSeats(Integer.parseInt(txtMinSeats.getText()));
        car.setMaxSeats(Integer.parseInt(txtMaxSeats.getText()));
        car.setManufacturedYear(Integer.parseInt(txtMfdYr.getText()));
        car.setMaintenanceCert(cbMaintenanceCert.isSelected());
        car.setAvailable(cbAvailable.isSelected());
        car.setSerialNum(Integer.parseInt(txtSerialNum.getText()));
        car.setLastUpdatedDate();
        JOptionPane.showMessageDialog(null, "New Car Added Successfully");

        txtCity.setText("");
        txtModelNum.setText("");
        txtBrand.setText("");
        txtMinSeats.setText("");
        txtMaxSeats.setText("");
        txtSerialNum.setText("");
        txtMfdYr.setText("");
        cbAvailable.setSelected(false);
        cbMaintenanceCert.setSelected(false);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        bottomPanel.remove(this);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnBack1;
    private javax.swing.JCheckBox cbAvailable;
    private javax.swing.JCheckBox cbMaintenanceCert;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccNo1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalance2;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblBankName2;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JLabel lblRoutingNo1;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMfdYr;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables
}
