/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Date Oct 5 2019
 * @author rashmirj
 * 
 * Panel to hold the filtered list from the first filter done by the user
 * User can further filter on the first filter over here
 */
public class FilterResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterResultsPanel
     */
    private CarList carDir;
    private JPanel bottomPanel;
    private List<Car> results;

    public FilterResultsPanel(JPanel bottomPanel, CarList carDir, List<Car> results) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.carDir = carDir;
        this.results = results;
        populate(results);
    }

    public void populate(List<Car> cars) {
        DefaultTableModel dtm = (DefaultTableModel) tblDirectory.getModel();
        dtm.setRowCount(0);

        for (Car a : cars) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getModelNum();
            row[2] = a.getBrand();
            row[3] = a.getMinSeats();
            row[4] = a.getMaxSeats();
            row[5] = a.getManufacturedYear();
            if (a.isMaintenanceCert()) {
                row[6] = "Valid";
            } else {
                row[6] = "Expired";
            }

            if (a.isAvailable()) {
                row[7] = "Available";
            } else {
                row[7] = "Not Available";
            }
            row[8] = a.getSerialNum();
            row[9] = a.getLastUpdatedDate();
            dtm.addRow(row);
        }

        DefaultTableModel dtm2 = (DefaultTableModel) tblBrand.getModel();
        dtm2.setRowCount(0);

        for (String b : carDir.getCarBrands(results)) {
            Object[] rowB = new Object[dtm2.getColumnCount()];
            rowB[0] = b;
            dtm2.addRow(rowB);
        }

        lblCarsAvl.setText(String.valueOf(carDir.getAvlCars(cars)));
        lblCarsNotAvl.setText(String.valueOf(carDir.getNotAvlCars(cars)));
        lblLastUpdatedDate.setText(String.valueOf(carDir.getLastUpd(cars)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblRoutingNo5 = new javax.swing.JLabel();
        lblRoutingNo6 = new javax.swing.JLabel();
        lblRoutingNo7 = new javax.swing.JLabel();
        lblRoutingNo8 = new javax.swing.JLabel();
        btnFirstAvl = new javax.swing.JButton();
        lblCarsAvl = new javax.swing.JLabel();
        lblCarsNotAvl = new javax.swing.JLabel();
        lblLastUpdatedDate = new javax.swing.JLabel();
        lblRoutingNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrand = new javax.swing.JTable();
        lblRoutingNo4 = new javax.swing.JLabel();
        lblRoutingNo3 = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        cFilters = new javax.swing.JComboBox<>();
        lblRoutingNo9 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtMax = new javax.swing.JTextField();
        lblMin = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        lblRoutingNo11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 153));
        setPreferredSize(new java.awt.Dimension(1365, 750));

        lblView.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblView.setForeground(new java.awt.Color(255, 255, 255));
        lblView.setText("Search Results");

        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "Model Number", "Brand", "Min. Seats", "Max. Seats", "Mfd. Yr.", "Maintenance Cert. Status", "Available", "Serial Num.", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDirectory);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 153));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRoutingNo5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo5.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo5.setText("Number of cars available:");

        lblRoutingNo6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo6.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo6.setText("All Car manufactures owned:");

        lblRoutingNo7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo7.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo7.setText("Last time fleet was updated:");

        lblRoutingNo8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo8.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo8.setText("Number of cars not available:");

        btnFirstAvl.setBackground(new java.awt.Color(255, 255, 255));
        btnFirstAvl.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnFirstAvl.setForeground(new java.awt.Color(255, 0, 153));
        btnFirstAvl.setText("Go");
        btnFirstAvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvlActionPerformed(evt);
            }
        });

        lblCarsAvl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCarsAvl.setForeground(new java.awt.Color(255, 255, 255));

        lblCarsNotAvl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCarsNotAvl.setForeground(new java.awt.Color(255, 255, 255));

        lblLastUpdatedDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLastUpdatedDate.setForeground(new java.awt.Color(255, 255, 255));

        lblRoutingNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo.setText("Quick Info based on your search results: ");

        tblBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brands"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBrand);

        lblRoutingNo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo4.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo4.setText("Find me the first available car from the list above : ");

        lblRoutingNo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo3.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo3.setText("Filter Search Results:");

        btnFilter.setBackground(new java.awt.Color(255, 255, 255));
        btnFilter.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(255, 0, 153));
        btnFilter.setText("Filter Results");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        cFilters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brand of the car", "Manufactured year of the car", "Seats required in a car", "Serial Number of the car", "Model Number of the car", "City where the car belongs", "Maintenence certificate expired" }));
        cFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFiltersActionPerformed(evt);
            }
        });

        lblRoutingNo9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo9.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo9.setText("Filter Condition -");

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 153));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtMax.setEnabled(false);

        lblMin.setText("           ");

        lblMax.setText("           ");

        lblRoutingNo11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo11.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo11.setText("Filter -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRoutingNo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFirstAvl)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoutingNo3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lblRoutingNo9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblRoutingNo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRoutingNo11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMin)
                                        .addGap(154, 154, 154)
                                        .addComponent(lblMax)
                                        .addGap(88, 88, 88)))))
                        .addGap(132, 132, 132)
                        .addComponent(btnFilter)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(631, 631, 631)
                        .addComponent(lblRoutingNo6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRoutingNo7)
                            .addComponent(lblRoutingNo8)
                            .addComponent(lblRoutingNo5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarsAvl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarsNotAvl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastUpdatedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(337, 337, 337)
                        .addComponent(lblView))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblView)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirstAvl)
                            .addComponent(lblRoutingNo4))
                        .addGap(12, 12, 12)
                        .addComponent(lblRoutingNo)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoutingNo5)
                                    .addComponent(lblCarsAvl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoutingNo8)
                                    .addComponent(lblCarsNotAvl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblRoutingNo6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblRoutingNo7))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLastUpdatedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblRoutingNo3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoutingNo9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFilter)
                            .addComponent(btnReset)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRoutingNo11)
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMin)
                                    .addComponent(lblMax))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        bottomPanel.remove(this);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFirstAvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvlActionPerformed
        // TODO add your handling code here:
        List<Car> firstAvlCar = carDir.getFirstAvlCar(results);
        if (firstAvlCar.size() > 0) {
            populate(firstAvlCar);
        } else {
            JOptionPane.showMessageDialog(null, "No results found, change search parameter and try again!");
        }
    }//GEN-LAST:event_btnFirstAvlActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        int selectedDD = cFilters.getSelectedIndex();
        List<Car> filteredResults = new ArrayList<>();

        switch (selectedDD) {
            case 0: { //brand filter
                String brandCurr = txtSearchField.getText();
                if (brandCurr == null || brandCurr.equals("")) {
                    JOptionPane.showMessageDialog(null, "Brand cannot be empty!");
                    return;
                }
                filteredResults = carDir.filterBrand(brandCurr, results);
                break;
            }
            case 1: { //mfd year
                try {
                    Integer.parseInt(txtSearchField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please input a valid Manufactured year for the car!");
                    return;
                }

                filteredResults = carDir.filterYear(Integer.parseInt(txtSearchField.getText()), results);
                break;
            }
            case 2: {
                try {
                    Integer.parseInt(txtSearchField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please input a valid minimum number of seats!");
                    return;
                }
                try {
                    Integer.parseInt(txtMax.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please input a valid maximum number of seats!!");
                    return;
                }

                if (Integer.parseInt(txtMax.getText()) < Integer.parseInt(txtSearchField.getText())) {
                    JOptionPane.showMessageDialog(null, "Please ensure minimum is less than the maximum number of seats!!");
                    return;
                }

                filteredResults = carDir.filterSeats(Integer.parseInt(txtSearchField.getText()), Integer.parseInt(txtMax.getText()), results);
                break;
            }
            case 3: { //serial number
                try {
                    Integer.parseInt(txtSearchField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Please input a valid serial number!");
                    return;
                }
                filteredResults = carDir.filterSerialNum(Integer.parseInt(txtSearchField.getText()), results);
                break;
            }
            case 4: { //model num
                String modelCurr = txtSearchField.getText();
                if (modelCurr == null || modelCurr.equals("")) {
                    JOptionPane.showMessageDialog(null, "Model Number cannot be empty!");
                    return;
                }
                filteredResults = carDir.filterModelNum(txtSearchField.getText(), results);
                break;
            }
            case 5: { //city
                String cityCurr = txtSearchField.getText();
                if (cityCurr == null || cityCurr.equals("")) {
                    JOptionPane.showMessageDialog(null, "City cannot be empty!");
                    return;
                }
                filteredResults = carDir.filterCity(txtSearchField.getText(), results);
                break;
            }
            case 6: { //maintenance expired
                filteredResults = carDir.filterEXpMCert(carDir.getCars());
                break;
            }

        }

        if (filteredResults.size() > 0) {
            populate(filteredResults);
        } else {
            JOptionPane.showMessageDialog(null, "No results found, change search parameter and try again!");
        }
        /*String fltrCity = txtCity.getText();
        String fltrModelNum = txtModelNum.getText();
        String fltrBrand = txtBrand.getText();
        int fltrMinSeats = Integer.parseInt(txtMinSeats.getText());
        int fltrMaxSeats = Integer.parseInt(txtMaxSeats.getText());
        int fltrMfdYr = Integer.parseInt(txtMfdYr.getText());
        Boolean fltrMaintenanceCert = cbMaintenanceCert.isSelected();
        Boolean fltrAvailable = cbAvailable.isSelected();
        int fltrSerialNum = Integer.parseInt(txtSerialNum.getText());*/

    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
            int selectedDD = cFilters.getSelectedIndex();
        if (selectedDD == 2) {
            txtMax.setEnabled(true);
            lblMin.setText("MIN SEATS");
            lblMax.setText("MAX SEATS");
            txtSearchField.setEnabled(true);
        } else if (selectedDD == 6) {
            txtMax.setEnabled(false);
            lblMin.setText("");
            txtSearchField.setEnabled(false);
            lblMax.setText("");
        } else {
            txtMax.setEnabled(false);
            lblMin.setText("");
            txtSearchField.setEnabled(true);
            lblMax.setText("");
        }
       populate(this.results);
        txtMax.setText("");
        txtSearchField.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void cFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFiltersActionPerformed
        // TODO add your handling code here:
        int selectedDD = cFilters.getSelectedIndex();
        if (selectedDD == 2) {
            txtMax.setEnabled(true);
            lblMin.setText("MIN SEATS");
            lblMax.setText("MAX SEATS");
            txtSearchField.setEnabled(true);
        } else if (selectedDD == 6) {
            txtMax.setEnabled(false);
            lblMin.setText("");
            txtSearchField.setEnabled(false);
            lblMax.setText("");
        } else {
            txtMax.setEnabled(false);
            lblMin.setText("");
            txtSearchField.setEnabled(true);
            lblMax.setText("");
        }
    }//GEN-LAST:event_cFiltersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnFirstAvl;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cFilters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarsAvl;
    private javax.swing.JLabel lblCarsNotAvl;
    private javax.swing.JLabel lblLastUpdatedDate;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JLabel lblRoutingNo11;
    private javax.swing.JLabel lblRoutingNo3;
    private javax.swing.JLabel lblRoutingNo4;
    private javax.swing.JLabel lblRoutingNo5;
    private javax.swing.JLabel lblRoutingNo6;
    private javax.swing.JLabel lblRoutingNo7;
    private javax.swing.JLabel lblRoutingNo8;
    private javax.swing.JLabel lblRoutingNo9;
    private javax.swing.JLabel lblView;
    private javax.swing.JTable tblBrand;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
}
