/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarList;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Date: Oct 5 2019
 * @author rashmirj
 * 
 * ALlows user to view the details entered. If user wishes to, user can update and save the data
 * user can even choose to cancel the changes made 
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private CarList carDir;
    private Car car;
    private JPanel bottomPanel;

    public ViewPanel(JPanel bottomPanel, Car car, CarList carDir) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.carDir = carDir;
        this.car = car;

        btnSave.setEnabled(false);

        txtCity.setText(car.getCity());
        txtModelNum.setText(car.getModelNum());
        txtBrand.setText(car.getBrand());
        txtMinSeats.setText(String.valueOf(car.getMinSeats()));
        txtMaxSeats.setText(String.valueOf(car.getMaxSeats()));
        txtMfdYr.setText(String.valueOf(car.getManufacturedYear()));
        cbMaintenanceCert.setSelected(car.isMaintenanceCert());
        cbAvailable.setSelected(car.isAvailable());
        txtSerialNum.setText(String.valueOf(car.getSerialNum()));
        txtLastUpd.setText(String.valueOf(car.getLastUpdatedDate()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        lblRoutingNo1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblAccNo1 = new javax.swing.JLabel();
        lblBankName1 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblBankName2 = new javax.swing.JLabel();
        lblBalance2 = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtLastUpd = new javax.swing.JTextField();
        txtMinSeats = new javax.swing.JTextField();
        cbMaintenanceCert = new javax.swing.JCheckBox();
        lblRoutingNo = new javax.swing.JLabel();
        cbAvailable = new javax.swing.JCheckBox();
        txtMaxSeats = new javax.swing.JTextField();
        txtMfdYr = new javax.swing.JTextField();
        lblAccNo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblView = new javax.swing.JLabel();
        lblBalance3 = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 0, 153));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 153));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setText("Minimum Seats *");

        lblRoutingNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo1.setText("Maximum Seats *");

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 0, 153));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblAccNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAccNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccNo1.setText("Manufactured Year *");

        lblBankName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName1.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName1.setText("Maintenance Certification Done *");

        txtCity.setEditable(false);
        txtCity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblBankName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName2.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName2.setText("Available *");

        lblBalance2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance2.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance2.setText("Serial Number *");

        txtModelNum.setEditable(false);
        txtModelNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtBrand.setEditable(false);
        txtBrand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtLastUpd.setEditable(false);
        txtLastUpd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtLastUpd.setEnabled(false);

        txtMinSeats.setEditable(false);
        txtMinSeats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        cbMaintenanceCert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cbMaintenanceCert.setEnabled(false);

        lblRoutingNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRoutingNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNo.setText("City *");

        cbAvailable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cbAvailable.setEnabled(false);

        txtMaxSeats.setEditable(false);
        txtMaxSeats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtMfdYr.setEditable(false);
        txtMfdYr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblAccNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAccNo.setForeground(new java.awt.Color(255, 255, 255));
        lblAccNo.setText("Model Number *");

        lblBankName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName.setText("Brand *");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 0, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 0, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblView.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblView.setForeground(new java.awt.Color(255, 255, 255));
        lblView.setText("View/Update Car Details");

        lblBalance3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBalance3.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance3.setText("Last Updated On *");

        txtSerialNum.setEditable(false);
        txtSerialNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBack)
                        .addGap(266, 266, 266)
                        .addComponent(lblView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoutingNo)
                                    .addComponent(lblAccNo)
                                    .addComponent(lblBankName)
                                    .addComponent(lblBalance)
                                    .addComponent(lblRoutingNo1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtModelNum)
                                            .addComponent(txtCity)
                                            .addComponent(txtBrand)
                                            .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAccNo1)
                                            .addComponent(lblBankName1))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbMaintenanceCert)
                                            .addComponent(txtMfdYr, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBankName2)
                                            .addComponent(lblBalance2))
                                        .addGap(185, 185, 185)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbAvailable)
                                            .addComponent(txtLastUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblBalance3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(26, 26, 26)
                                .addComponent(btnUpdate)
                                .addGap(30, 30, 30)
                                .addComponent(btnCancel)))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBankName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBalance))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoutingNo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRoutingNo)
                                .addGap(30, 30, 30)
                                .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAccNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMfdYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBankName1)
                                    .addComponent(cbMaintenanceCert))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAvailable)
                                    .addComponent(lblBankName2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBalance2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBalance3)
                            .addComponent(txtLastUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        txtCity.setText("");
        txtModelNum.setText("");
        txtBrand.setText("");
        txtMinSeats.setText("");
        txtMaxSeats.setText("");
        txtSerialNum.setText("");
        txtMfdYr.setText("");
        cbAvailable.setSelected(false);
        cbMaintenanceCert.setSelected(false);

        this.bottomPanel.remove(this);
        CardLayout layout = (CardLayout) this.bottomPanel.getLayout();

        Component[] comps = this.bottomPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageCarsPanel) {
                ManageCarsPanel manageP = (ManageCarsPanel) comp;
                manageP.populate(carDir.getCars());
            }
        }

        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtCity.setText(car.getCity());
        txtModelNum.setText(car.getModelNum());
        txtBrand.setText(car.getBrand());
        txtMinSeats.setText(String.valueOf(car.getMinSeats()));
        txtMaxSeats.setText(String.valueOf(car.getMaxSeats()));
        txtMfdYr.setText(String.valueOf(car.getManufacturedYear()));
        cbMaintenanceCert.setSelected(car.isMaintenanceCert());
        cbAvailable.setSelected(car.isAvailable());
        txtSerialNum.setText(String.valueOf(car.getSerialNum()));
        txtLastUpd.setText(String.valueOf(car.getLastUpdatedDate()));
        txtCity.setEditable(false);
        txtModelNum.setEditable(false);
        txtBrand.setEditable(false);
        txtMinSeats.setEditable(false);
        txtMaxSeats.setEditable(false);
        txtMfdYr.setEditable(false);
        cbMaintenanceCert.setEnabled(false);
        cbAvailable.setEnabled(false);
        txtSerialNum.setEditable(false);

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Custom validations
        String cityCurr = txtCity.getText();
        String modelCurr = txtModelNum.getText();
        String brandCurr = txtBrand.getText();

        if (cityCurr == null || cityCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "City cannot be empty!");
            return;
        }

        if (modelCurr == null || modelCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "Model Number cannot be empty!");
            return;
        }
        if (brandCurr == null || brandCurr.equals("")) {
            JOptionPane.showMessageDialog(null, "Brand cannot be empty!");
            return;
        }
        try {
            Integer.parseInt(txtMinSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid minimum number of seats!");
            return;
        }
        try {
            Integer.parseInt(txtMaxSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid maximum number of seats!!");
            return;
        }

        if (Integer.parseInt(txtMaxSeats.getText()) < Integer.parseInt(txtMinSeats.getText())) {
            JOptionPane.showMessageDialog(null, "Please ensure minimum is less than the maximum number of seats!!");
            return;
        }

        try {
            Integer.parseInt(txtMfdYr.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid Manufactured year for the car!");
            return;
        }

        try {
            Integer.parseInt(txtSerialNum.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid serial number!");
            return;
        }

        car.setCity(txtCity.getText());
        car.setModelNum(txtModelNum.getText());
        car.setBrand(txtBrand.getText());
        car.setMinSeats(Integer.parseInt(txtMinSeats.getText()));
        car.setMaxSeats(Integer.parseInt(txtMaxSeats.getText()));
        car.setManufacturedYear(Integer.parseInt(txtMfdYr.getText()));
        car.setMaintenanceCert(cbMaintenanceCert.isSelected());
        car.setAvailable(cbAvailable.isSelected());
        car.setSerialNum(Integer.parseInt(txtSerialNum.getText()));
        car.setLastUpdatedDate();

        txtCity.setEditable(false);
        txtModelNum.setEditable(false);
        txtBrand.setEditable(false);
        txtMinSeats.setEditable(false);
        txtMaxSeats.setEditable(false);
        txtMfdYr.setEditable(false);
        cbMaintenanceCert.setEnabled(false);
        cbAvailable.setEnabled(false);
        txtSerialNum.setEditable(false);

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

        JOptionPane.showMessageDialog(null, "Car details updated successfully");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

        txtCity.setEditable(true);
        txtModelNum.setEditable(true);
        txtBrand.setEditable(true);
        txtMinSeats.setEditable(true);
        txtMaxSeats.setEditable(true);
        txtMfdYr.setEditable(true);
        cbMaintenanceCert.setEnabled(true);
        cbAvailable.setEnabled(true);
        txtSerialNum.setEditable(true);

    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbAvailable;
    private javax.swing.JCheckBox cbMaintenanceCert;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccNo1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalance2;
    private javax.swing.JLabel lblBalance3;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblBankName2;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JLabel lblRoutingNo1;
    private javax.swing.JLabel lblView;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastUpd;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMfdYr;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables
}
